
export const nacionalidades = [
  "Afgana",
  "Albanesa",
  "Alemana",
  "Andorrana",
  "Angoleña",
  "Antiguana",
  "Saudí",
  "Argelina",
  "Argentina",
  "Armenia",
  "Australiana",
  "Austríaca",
  "Azerbaiyana",
  "Bahameña",
  "Bangladesí",
  "Barbadense",
  "Bareiní",
  "Belga",
  "Beliceña",
  "Beninesa",
  "Bielorrusa",
  "Birmana",
  "Boliviana",
  "Bosnia",
  "Botsuana",
  "Brasileña",
  "Británica",
  "Bruneana",
  "Búlgara",
  "Burkinesa",
  "Burundesa",
  "Butanesa",
  "Cabo Verdiana",
  "Camboyana",
  "Camerunesa",
  "Canadiense",
  "Catarí",
  "Centroafricana",
  "Chadiana",
  "Checa",
  "Chilena",
  "China",
  "Chipriota",
  "Colombiana",
  "Comorense",
  "Congoleña",
  "Norcoreana",
  "Surcoreana",
  "Costamarfileña",
  "Costarricense",
  "Croata",
  "Cubana",
  "Danesa",
  "Dominicana",
  "Ecuatoguineana",
  "Ecuatoriana",
  "Egipcia",
  "Salvadoreña",
  "Emiratí",
  "Eritrea",
  "Eslovaca",
  "Eslovena",
  "Española",
  "Estadounidense",
  "Estonia",
  "Etíope",
  "Filipina",
  "Finlandesa",
  "Fiyiana",
  "Francesa",
  "Gabonense",
  "Gambiana",
  "Georgiana",
  "Ghanesa",
  "Granadina",
  "Griega",
  "Guatemalteca",
  "Guineana",
  "Guineana-Bisáu",
  "Guyanesa",
  "Haitiana",
  "Hondureña",
  "Húngara",
  "India",
  "Indonesa",
  "Iraquí",
  "Iraní",
  "Irlandesa",
  "Islandesa",
  "Israelí",
  "Italiana",
  "Jamaicana",
  "Japonesa",
  "Jordana",
  "Kazaja",
  "Keniata",
  "Kirguisa",
  "Kiribatiana",
  "Kuwaití",
  "Laosiana",
  "Lesotense",
  "Letona",
  "Libanesa",
  "Liberiana",
  "Libia",
  "Liechtensteiniana",
  "Lituana",
  "Luxemburguesa",
  "Macedonia",
  "Malasia",
  "Malauí",
  "Maldiva",
  "Maliense",
  "Maltesa",
  "Marfileña",
  "Marroquí",
  "Marshallesa",
  "Mauriciana",
  "Mauritana",
  "Mexicana",
  "Micronesia",
  "Moldava",
  "Monegasca",
  "Mongola",
  "Montenegrina",
  "Mozambiqueña",
  "Namibia",
  "Nauruana",
  "Nepalí",
  "Nicaragüense",
  "Nigeriana",
  "Nigerina",
  "Noruega",
  "Neozelandesa",
  "Omana",
  "Neerlandesa",
  "Pakistaní",
  "Palaosiana",
  "Palestina",
  "Panameña",
  "Papú",
  "Paraguaya",
  "Peruana",
  "Polaca",
  "Portuguesa",
  "Qatarí",
  "Rumano",
  "Ruandesa",
  "Rusa",
  "Samoana",
  "Sancristobaleña",
  "Sanvicentina",
  "Santa Lucía",
  "Santomense",
  "Senegalesa",
  "Serbia",
  "Seychellense",
  "Sierraleonesa",
  "Singapurense",
  "Siria",
  "Somalí",
  "Sri Lanka",
  "Suazilandesa",
  "Sudafricana",
  "Sudanesa",
  "Sueca",
  "Suiza",
  "Surinamesa",
  "Tailandesa",
  "Tanzana",
  "Tayika",
  "Timorense",
  "Togolesa",
  "Tonga",
  "Trinitense",
  "Tunecina",
  "Turca",
  "Turkmena",
  "Tuvaluana",
  "Ucraniana",
  "Ugandesa",
  "Uruguaya",
  "Uzbeca",
  "Vanuatuense",
  "Vaticana",
  "Venezolana",
  "Vietnamita",
  "Yemení",
  "Yibutiana",
  "Zambiana",
  "Zimbabuense"
];

export const comunasDeChile = [
  "Alhué", "Buin", "Calera de Tango", "Cerrillos", "Cerro Navia", "Colina", "Conchalí", "Curacaví", "El Bosque",
  "El Monte", "Estación Central", "Huechuraba", "Independencia", "Isla de Maipo", "La Cisterna", "La Florida",
  "La Granja", "La Pintana", "La Reina", "Lampa", "Las Condes", "Lo Barnechea", "Lo Espejo", "Lo Prado",
  "Macul", "Maipú", "María Pinto", "Melipilla", "Ñuñoa", "Padre Hurtado", "Paine", "Pedro Aguirre Cerda",
  "Peñaflor", "Peñalolén", "Pirque", "Providencia", "Pudahuel", "Puente Alto", "Quilicura", "Quinta Normal",
  "Recoleta", "Renca", "San Bernardo", "San Joaquín", "San José de Maipo", "San Miguel", "San Pedro", "San Ramón",
  "Santiago", "Talagante", "Tiltil", "Vitacura", "Arica", "Camarones", "Putre", "General Lagos", "Iquique",
  "Alto Hospicio", "Pozo Almonte", "Camiña", "Colchane", "Huara", "Pica", "Antofagasta", "Mejillones", "Sierra Gorda",
  "Taltal", "Calama", "Ollagüe", "San Pedro de Atacama", "Tocopilla", "María Elena", "Copiapó", "Caldera",
  "Tierra Amarilla", "Chañaral", "Diego de Almagro", "Vallenar", "Alto del Carmen", "Freirina", "Huasco",
  "La Serena", "Coquimbo", "Andacollo", "La Higuera", "Paiguano", "Vicuña", "Illapel", "Canela", "Los Vilos",
  "Salamanca", "Ovalle", "Combarbalá", "Monte Patria", "Punitaqui", "Río Hurtado", "Valparaíso", "Casablanca",
  "Concón", "Juan Fernández", "Puchuncaví", "Quintero", "Viña del Mar", "Isla de Pascua", "Los Andes", "Calle Larga",
  "Rinconada", "San Esteban", "La Ligua", "Cabildo", "Papudo", "Petorca", "Zapallar", "Quillota", "Calera",
  "Hijuelas", "La Cruz", "Nogales", "San Antonio", "Algarrobo", "Cartagena", "El Quisco", "El Tabo", "San Sebastián",
  "Santo Domingo", "San Felipe", "Catemu", "Llaillay", "Panquehue", "Putaendo", "Santa María", "Quilpué", "Limache",
  "Olmué", "Villa Alemana", "Rancagua", "Codegua", "Coinco", "Coltauco", "Doñihue", "Graneros", "Las Cabras",
  "Machalí", "Malloa", "Mostazal", "Olivar", "Peumo", "Pichidegua", "Quinta de Tilcoco", "Rengo", "Requínoa",
  "San Vicente", "Pichilemu", "La Estrella", "Litueche", "Marchigüe", "Navidad", "Paredones", "San Fernando",
  "Chépica", "Chimbarongo", "Lolol", "Nancagua", "Palmilla", "Peralillo", "Placilla", "Pumanque", "Santa Cruz",
  "Talca", "Constitución", "Curepto", "Empedrado", "Maule", "Pelarco", "Pencahue", "Río Claro", "San Clemente",
  "San Rafael", "Cauquenes", "Chanco", "Pelluhue", "Curicó", "Hualañé", "Licantén", "Molina", "Rauco", "Romeral",
  "Sagrada Familia", "Teno", "Vichuquén", "Linares", "Colbún", "Longaví", "Parral", "Retiro", "San Javier",
  "Villa Alegre", "Yerbas Buenas", "Chillán", "Bulnes", "Chillán Viejo", "El Carmen", "Pemuco", "Pinto", "Quillón",
  "San Ignacio", "Yungay", "Quirihue", "Cobquecura", "Coelemu", "Ninhue", "Portezuelo", "Ránquil", "Treguaco",
  "San Carlos", "Coihueco", "San Fabián", "San Nicolás", "Arauco", "Cañete", "Contulmo", "Curanilahue", "Lebu",
  "Los Álamos", "Tirúa", "Alto Biobío", "Antuco", "Cabrero", "Laja", "Los Ángeles", "Mulchén", "Nacimiento",
  "Negrete", "Quilaco", "Quilleco", "San Rosendo", "Santa Bárbara", "Tucapel", "Yumbel", "Chiguayante", "Concepción",
  "Coronel", "Florida", "Hualpén", "Hualqui", "Lota", "Penco", "San Pedro de la Paz", "Santa Juana", "Talcahuano",
  "Tomé", "Temuco", "Carahue", "Cunco", "Curarrehue", "Freire", "Galvarino", "Gorbea", "Lautaro", "Loncoche",
  "Melipeuco", "Nueva Imperial", "Padre Las Casas", "Perquenco", "Pitrufquén", "Pucón", "Saavedra", "Teodoro Schmidt",
  "Toltén", "Vilcún", "Villarrica", "Angol", "Collipulli", "Curacautín", "Ercilla", "Lonquimay", "Los Sauces",
  "Lumaco", "Purén", "Renaico", "Traiguén", "Victoria", "Valdivia", "Corral", "Lanco", "Los Lagos", "Máfil",
  "Mariquina", "Paillaco", "Panguipulli", "La Unión", "Futrono", "Lago Ranco", "Río Bueno", "Osorno", "Puerto Octay",
  "Purranque", "Puyehue", "Río Negro", "San Juan de la Costa", "San Pablo", "Chaitén", "Futaleufú", "Hualaihué",
  "Palena", "Puerto Montt", "Calbuco", "Cochamó", "Fresia", "Frutillar", "Los Muermos", "Llanquihue", "Maullín",
  "Puerto Varas", "Coyhaique", "Lago Verde", "Aysén", "Cisnes", "Guaitecas", "Cochrane", "O'Higgins", "Tortel",
  "Chile Chico", "Río Ibáñez", "Punta Arenas", "Laguna Blanca", "Río Verde", "San Gregorio", "Cabo de Hornos",
  "Antártica", "Porvenir", "Primavera", "Timaukel", "Natales", "Torres del Paine"
];

export const AFP = [
  "Capital",
  "Cuprum",
  "Habitat",
  "Modelo",
  "No está en AFP",
  "PlanVital",
  "ProVida",
  "Uno"
]

export const SALUD = [
  "Banmedica",
  "Chuquicamata",
  "Colmena",
  "Consalud",
  "Cruz Blanca",
  "Cruz del Norte",
  "Ferrosalud",
  "Fonasa",
  "Institución de Salud Previsional Fusat Ltda.",
  "Isapre Bco. Estado",
  "ISAPRE ESENCIAL",
  "Nueva Mas Vida",
  "Rio Blanco",
  "San Lorenzo isapre Ltda.",
  "Sin Isapre",
  "VidaTres"
]


export const contratosData = [
  {
    rut: "12.345.678-9",
    nombre: "Ana María Soto Pérez",
    inicio: "2023-01-15",
    termino: "2024-01-15",
    liquido: "650.789", // Example of random liquid value
    cargo: "27 Electrico 2",
    email: "ana.soto@example.com",
    folio: "310", // Example of random folio
  },
  {
    rut: "13.456.789-0",
    nombre: "Pedro Antonio González Rojas",
    inicio: "2023-02-20",
    termino: "2024-02-20",
    liquido: "812.345",
    cargo: "Mecánico Industrial",
    email: "pedro.gonzalez@example.com",
    folio: "723",
  },
  {
    rut: "14.567.890-1",
    nombre: "Sofía Alejandra Díaz Castro",
    inicio: "2023-03-10",
    termino: "2024-03-10",
    liquido: "420.111",
    cargo: "Ingeniero de Proyectos",
    email: "sofia.diaz@example.com",
    folio: "187",
  },
  {
    rut: "15.678.901-2",
    nombre: "Juan Carlos Muñoz Silva",
    inicio: "2023-04-05",
    termino: "2024-04-05",
    liquido: "987.654",
    cargo: "Supervisor de Obra",
    email: "juan.munoz@example.com",
    folio: "562",
  },
  {
    rut: "16.789.012-3",
    nombre: "Laura Beatriz Herrera Vargas",
    inicio: "2023-05-01",
    termino: "2024-05-01",
    liquido: "350.999",
    cargo: "Administrador de Contratos",
    email: "laura.herrera@example.com",
    folio: "915",
  },
  {
    rut: "17.890.123-4",
    nombre: "Carlos Eduardo Gatica Torres",
    inicio: "2023-06-12",
    termino: "2024-06-12",
    liquido: "721.450",
    cargo: "Soldador Calificado",
    email: "carlos.gatica@example.com",
    folio: "401",
  },
  {
    rut: "18.901.234-5",
    nombre: "María Fernanda Guzmán Tapia",
    inicio: "2023-07-08",
    termino: "2024-07-08",
    liquido: "580.000",
    cargo: "Analista Contable",
    email: "maria.guzman@example.com",
    folio: "233",
  },
  {
    rut: "19.012.345-6",
    nombre: "Diego Ignacio Romero Fuentes",
    inicio: "2023-08-18",
    termino: "2024-08-18",
    liquido: "910.250",
    cargo: "Técnico en Climatización",
    email: "diego.romero@example.com",
    folio: "876",
  },
  {
    rut: "20.123.456-7",
    nombre: "Valentina Paz Orellana Soto",
    inicio: "2023-09-22",
    termino: "2024-09-22",
    liquido: "499.700",
    cargo: "Asistente Administrativa",
    email: "valentina.orellana@example.com",
    folio: "129",
  },
  {
    rut: "21.234.567-8",
    nombre: "Gabriel Andrés Pérez Rojas",
    inicio: "2023-10-01",
    termino: "2024-10-01",
    liquido: "765.100",
    cargo: "Jefe de Bodega",
    email: "gabriel.perez@example.com",
    folio: "605",
  },
  {
    rut: "10.111.222-3",
    nombre: "Camila Belén Soto Muñoz",
    inicio: "2023-11-05",
    termino: "2024-11-05",
    liquido: "380.500",
    cargo: "Secretaria Ejecutiva",
    email: "camila.soto@example.com",
    folio: "941",
  },
  {
    rut: "11.222.333-4",
    nombre: "Francisco Javier Rojas Díaz",
    inicio: "2023-12-10",
    termino: "2024-12-10",
    liquido: "850.000",
    cargo: "Conductor Clase A4",
    email: "francisco.rojas@example.com",
    folio: "378",
  },
  {
    rut: "12.333.444-5",
    nombre: "Daniela Constanza Castro Vargas",
    inicio: "2024-01-01",
    termino: "2025-01-01",
    liquido: "510.200",
    cargo: "Diseñador Gráfico",
    email: "daniela.castro@example.com",
    folio: "290",
  },
  {
    rut: "13.444.555-6",
    nombre: "Sebastián Andrés Silva Torres",
    inicio: "2024-02-14",
    termino: "2025-02-14",
    liquido: "975.000",
    cargo: "Especialista en Redes",
    email: "sebastian.silva@example.com",
    folio: "704",
  },
  {
    rut: "14.555.666-7",
    nombre: "Andrea Carolina Tapia Fuentes",
    inicio: "2024-03-20",
    termino: "2025-03-20",
    liquido: "400.600",
    cargo: "Encargado de Compras",
    email: "andrea.tapia@example.com",
    folio: "155",
  },
  {
    rut: "15.666.777-8",
    nombre: "Pablo Ignacio Gatica Guzmán",
    inicio: "2024-04-25",
    termino: "2025-04-25",
    liquido: "625.800",
    cargo: "Técnico en Sonido",
    email: "pablo.gatica@example.com",
    folio: "831",
  },
  {
    rut: "16.777.888-9",
    nombre: "Josefa Paz Muñoz Orellana",
    inicio: "2024-05-01",
    termino: "2025-05-01",
    liquido: "330.150",
    cargo: "Asistente de Marketing",
    email: "josefa.munoz@example.com",
    folio: "267",
  },
  {
    rut: "17.888.999-0",
    nombre: "Felipe Alejandro Soto Pérez",
    inicio: "2024-06-07",
    termino: "2025-06-07",
    liquido: "950.000",
    cargo: "Operador de Maquinaria Pesada",
    email: "felipe.soto@example.com",
    folio: "599",
  },
  {
    rut: "18.999.000-1",
    nombre: "Martina Isidora Vargas Silva",
    inicio: "2024-07-12",
    termino: "2025-07-12",
    liquido: "470.300",
    cargo: "Enfermera Ocupacional",
    email: "martina.vargas@example.com",
    folio: "102",
  },
  {
    rut: "19.000.111-2",
    nombre: "Ignacio Daniel Torres Castro",
    inicio: "2024-08-01",
    termino: "2025-08-01",
    liquido: "780.999",
    cargo: "Desarrollador Web",
    email: "ignacio.torres@example.com",
    folio: "845",
  },
];
